# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BMS-MarvelVsDC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'SDWebImage' 

  # Pods for BMS-MarvelVsDC

  target 'BMS-MarvelVsDCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BMS-MarvelVsDCUITests' do
    # Pods for testing
  end

end
